### ISSUE TITLE
Не работает утилита

### ISSUE THREAD

**Issue by OlyoshaOlyosha** [YariKartoshe4ka/vk-messages-saver#20]
При скачивании и первом запуске `VK-MS.py` такая ошибка:

```BASH
Traceback (most recent call last):
  File "c:\Users\user\Downloads\vk-messages-saver-master\VK-MS.py", line 2, in <module>
    from vkms.main import main
  File "c:\Users\user\Downloads\vk-messages-saver-master\vkms\__init__.py", line 1, in <module>
    from .version import __version__, __version_tuple__
ImportError: cannot import name '__version__' from 'vkms.version' (c:\Users\user\Downloads\vk-messages-saver-master\vkms\version.py)
```

Я попытался халтурно исправить, создав `verison.py`:
```Python
__version__ = "1.0.0"
__version_tuple__ = (1, 0, 0)
```

Но появилась другая ошибка:
```BASH
usage: VK-MS.py [-h] [-o OUTDIR] [-i INCLUDE | -e EXCLUDE] [-v] {dump,parse,atch} ...
VK-MS.py: error: the following arguments are required: action
```

А через отладку `main.py` в `argparser.py` ошибка в этом:
```Python
def parse_args():
    args = parser.parse_args()
```

```BASH
File "C:\Users\user\Downloads\vk-messages-saver-master\vkms\argparser.py", line 162, in parse_args
    args = parser.parse_args()
  File "C:\Users\user\Downloads\vk-messages-saver-master\vkms\main.py", line 29, in main
    args = parse_args()
  File "C:\Users\user\Downloads\vk-messages-saver-master\VK-MS.py", line 5, in <module>
    main()
SystemExit: 2
```

Видимо, я что-то не так делаю, воспользоваться утилитой не могу. Сам `vkms` я скачал из [PyPI](https://pypi.org/project/vkms/)

**Comment by YariKartoshe4ka** [comment]
В [доке](https://github.com/YariKartoshe4ka/vk-messages-saver/blob/master/docs/DOCS.md) написано как использовать тулзу и какие параметры она принимает
Если хочешь установить версию из GitHub'а, то это можно сделать командой

```sh
pip install git+https://github.com/YariKartoshe4ka/vk-messages-saver
```
