### ISSUE TITLE
UnicodeEncodeError когда пытаюсь конвертировать дамп в html 

### ISSUE THREAD

**Issue by dimas257** [YariKartoshe4ka/vk-messages-saver#6]
После дампа, когда я прописываю `vkms parse`, получаю в ответ это:
```
C:\Users\dimas257\Desktop>vkms parse
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\dimas257\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\vkms.exe\__main__.py", line 7, in <module>
  File "C:\Users\dimas257\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\vkms\main.py", line 51, in main
    actions.parse(args.out_dir, args.include, args.exclude, args.fmt)
  File "C:\Users\dimas257\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\vkms\actions.py", line 181, in parse
    saver.save(out_dir, fmt, peer)
  File "C:\Users\dimas257\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\vkms\saver.py", line 20, in save
    globals()['save_' + fmt](out_dir, peer)
  File "C:\Users\dimas257\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\vkms\saver.py", line 38, in save_txt
    _convert_txt_msgs(peer.msgs, peer.account['id'], file)
  File "C:\Users\dimas257\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\vkms\saver.py", line 63, in _convert_txt_msgs
    file.write(f"[{msg.time()}] {username} {line}\n")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 29: character maps to <undefined>
```
В чём может быть проблема?
P.S. Платформа: **Windows 11 21H1**
P.P.S. Версия Python: **Python 3.10**

**Comment by dimas257** [comment]
Как я только что выяснил, \u2705 в юникоде - Галочка
![image](https://user-images.githubusercontent.com/65215768/224484577-fc7ecc24-b363-4b6c-a788-98bb428ed68c.png)

**Comment by dimas257** [comment]
`vkms parse -f html`:
```
C:\Users\dimas257\Desktop>vkms parse -f html
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\dimas257\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\vkms.exe\__main__.py", line 7, in <module>
  File "C:\Users\dimas257\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\vkms\main.py", line 51, in main
    actions.parse(args.out_dir, args.include, args.exclude, args.fmt)
  File "C:\Users\dimas257\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\vkms\actions.py", line 181, in parse
    saver.save(out_dir, fmt, peer)
  File "C:\Users\dimas257\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\vkms\saver.py", line 20, in save
    globals()['save_' + fmt](out_dir, peer)
  File "C:\Users\dimas257\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\vkms\saver.py", line 205, in save_html
    file.write(minify(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f49b' in position 120: character maps to <undefined>
```

**Comment by YariKartoshe4ka** [comment]
Быстрый фикс (установка dev версии vkms):

```sh
pip install git+https://github.com/YariKartoshe4ka/vk-messages-saver
```

На PyPI выложу несколько позже

**Comment by dimas257** [comment]
![image](https://user-images.githubusercontent.com/65215768/224512014-a68691f9-151f-42db-a184-5205b3f4a67e.png)

**Comment by YariKartoshe4ka** [comment]
Откройте новое issue. Если не жалко, то прикрепите sqlite файл этой переписки (в logs.txt можете узнать на какой переписке стопорится)

**Comment by YariKartoshe4ka** [comment]
Уже не надо, исправлено в #7

**Comment by dimas257** [comment]
Хорошо, спасибо
