### ISSUE TITLE
Диалог, состоящий из сообщений только одного участника, вызывает ошибку

### ISSUE THREAD

**Issue by YariKartoshe4ka** [YariKartoshe4ka/vk-messages-saver#7]
<details>
<summary>Скриншот</summary>

![скрин](https://user-images.githubusercontent.com/49284924/224540147-6b6268e6-69c3-4f47-9873-374994bc8c89.png)

</details>

```
Traceback (most recent call last):
  File "/home/yaroslav/Programming/Python3/Bash/vk-messages-saver/VK-MS.py", line 5, in <module>
    main()
  File "/home/yaroslav/Programming/Python3/Bash/vk-messages-saver/vkms/main.py", line 51, in main
    actions.parse(args.out_dir, args.include, args.exclude, args.fmt)
  File "/home/yaroslav/Programming/Python3/Bash/vk-messages-saver/vkms/actions.py", line 180, in parse
    peer = peers.Peer(session)
  File "/home/yaroslav/Programming/Python3/Bash/vk-messages-saver/vkms/peers.py", line 82, in __init__
    self.title = usernames[self.info['peer']['id']]
KeyError: #########
```

**Comment by YariKartoshe4ka** [comment]
Исправлено благодаря [2154f77](https://github.com/YariKartoshe4ka/vk-messages-saver/commit/2154f77b15831480e836839214a21ae70fa3f88b)
Решение - обновиться до последней dev версии:

```sh
pip install git+https://github.com/YariKartoshe4ka/vk-messages-saver
```
